# Generated by Django 5.0.1 on 2024-10-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_receipt_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
